### PR TITLE
Semantic

### PR DESCRIPTION
**Pull request by Sanderson239**

### CODE REVIEW

**Comment by HamidAghdaee** [comment]
nice initial work @Sanderson239. A couple of things:

1. Why are there no tests here? the App component test fails as well
2. The reducer seems very complex the way you've written it. Could you please simplify and/or write comments explaining what you're doing?

thanks.

**Comment by Sanderson239** [comment]
I'm working on the tests right now.
I'll add in some comments to the reducer. I just didn't like the format of the data I would be expected to retrieve from the Google Sheets API.

**Comment by HamidAghdaee** [comment]
Right on @Sanderson239 . what don't you like about the format of data from google?

**Comment by Sanderson239** [comment]
The sample data I saw organized part of the table data into an array of rows where each row was an array of strings. I wanted each cell and each row to have ids and be contained within objects organized by id. What's in the seed data file is what I would expect the data from google to look like.

**Comment by HamidAghdaee** [comment]
@Sanderson239 Interesting. Could you please share an example of what your store state looks like when populated by seed data through the reducer?

Why do you like this better?

thanks.

**Pull request merged**
